version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts1/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts1/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts1/stop_server
      timeout: 300
      runas: root